FROM ubuntu:22.04
RUN apt-get update && apt-get install -y nginx curl && rm -rf /var/lib/apt/lists/*
RUN rm -rf /var/www/html/*
COPY index.html /var/www/html/
EXPOSE 80
HEALTHCHECK --interval=5s --timeout=3s  --retries=3 --start-period=5s \
CMD curl -f http://localhost:80/ || exit 1
CMD ["sh","-c", "service nginx start && tail -f /dev/null"]


